export const classStats = {
  1: {
    hp: 4,
    mp: 4,
    health: 3,
    strength: 1,
    agility: 4,
    intelligence: 6,
    wisdom: 6,
    charisma: 2,
    physicalAttack: 3,
    magicAttack: 21,
  },
  2: {
    hp: 4,
    mp: 4,
    health: 3,
    strength: 5,
    agility: 6,
    intelligence: 4,
    wisdom: 2,
    charisma: 5,
    physicalAttack: 8,
    magicAttack: 17,
  },
  3: {
    hp: 4,
    mp: 4,
    health: 2,
    strength: 5,
    agility: 4,
    intelligence: 3,
    wisdom: 4,
    charisma: 4,
    physicalAttack: 15,
    magicAttack: 15,
  },
  4: {
    hp: 4,
    mp: 4,
    health: 2,
    strength: 5,
    agility: 7,
    intelligence: 5,
    wisdom: 4,
    charisma: 3,
    physicalAttack: 13,
    magicAttack: 13,
  },
  5: {
    hp: 4,
    mp: 4,
    health: 6,
    strength: 8,
    agility: 2,
    intelligence: 2,
    wisdom: 2,
    charisma: 4,
    physicalAttack: 25,
    magicAttack: 5,
  },
};
